### ISSUE TITLE
Vite 2.8.6下引入报错

### ISSUE THREAD

**Issue by blackbutton** [nshen/vite-plugin-cesium#23]
使用Vite创建项目，引入vite-plugin-cesium, 然后运行出现如下错误：
failed to load config from D:\code\html\vite-project\vite.config.ts
error when starting preview server:
TypeError: cesium is not a function
    at file:///D:/code/html/vite-project/vite.config.ts.js?t=1647506660917:6:13
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async loadConfigFromFile (D:\code\html\vite-project\node_modules\vite\dist\node\chunks\dep-9c153816.js:71326:31)
    at async resolveConfig (D:\code\html\vite-project\node_modules\vite\dist\node\chunks\dep-9c153816.js:70873:28)
    at async preview (D:\code\html\vite-project\node_modules\vite\dist\node\chunks\dep-9c153816.js:69518:20)
    at async CAC.<anonymous> (D:\code\html\vite-project\node_modules\vite\dist\node\cli.js:783:24)

**Comment by nshen** [comment]
哦？ 请问 install cesium 了吗？
