### ISSUE TITLE
use vite-plugin-cesium start project has error: Invalid define value (must be valid JSON syntax or a single identifier): /cesium/

### ISSUE THREAD

**Issue by wanglizhigs** [nshen/vite-plugin-cesium#3]
leo@leodeMacBook-Pro AESA-Visual-System % yarn dev
yarn run v1.22.10
warning package.json: No license field
$ vite
Pre-bundling dependencies:
  vue
  vuex
  vue-router
  cesium
(this will be run only when your dependencies or config have changed)
 > error: Invalid define value (must be valid JSON syntax or a single identifier): /cesium/

error when starting dev server:
Error: Build failed with 1 error:
error: Invalid define value (must be valid JSON syntax or a single identifier): /cesium/
    at failureErrorWithLog (/Users/leo/Desktop/leixiang/workspace/AESA-Visual-System/node_modules/esbuild/lib/main.js:1224:15)
    at buildResponseToResult (/Users/leo/Desktop/leixiang/workspace/AESA-Visual-System/node_modules/esbuild/lib/main.js:936:32)
    at /Users/leo/Desktop/leixiang/workspace/AESA-Visual-System/node_modules/esbuild/lib/main.js:1035:20
    at /Users/leo/Desktop/leixiang/workspace/AESA-Visual-System/node_modules/esbuild/lib/main.js:568:9
    at handleIncomingPacket (/Users/leo/Desktop/leixiang/workspace/AESA-Visual-System/node_modules/esbuild/lib/main.js:657:9)
    at Socket.readFromStdout (/Users/leo/Desktop/leixiang/workspace/AESA-Visual-System/node_modules/esbuild/lib/main.js:535:7)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by nshen** [comment]
@wanglizhigs hi could you try 1.2.2, see if it works

  "devDependencies": {

"vite-plugin-cesium": **"1.2.2",**

  }

**Comment by nshen** [comment]
hi @wanglizhigs  try 1.2.4 , I think it will be work.

```
 "devDependencies": {
    "vite": "^2.2.1",
    "vite-plugin-cesium": "^1.2.4",
    "cesium": "^1.80"
  }
```
