### ISSUE TITLE
Demo didn't build

### ISSUE THREAD

**Issue by eric-g-97477** [nshen/vite-plugin-cesium#42]
What I tried doing was:

1. git clone git@github.com:nshen/vite-plugin-cesium.git
2. cd vite-plugin-cesium/demo
3. yarn
4. yarn dev

The error output I received was:

```
(lm_env) ~/d/v/t/v/demo (main|✔) $ yarn dev                                                                                                                                                         14:27:14
yarn run v1.22.19
$ vite
✘ [ERROR] [plugin externalize-deps] Failed to resolve entry for package "vite-plugin-cesium". The package may have incorrect main/module/exports specified in its package.json.

    node_modules/esbuild/lib/main.js:1336:27:
      1336 │         let result = await callback({
           ╵                            ^

    at packageEntryFailure (file:///Users/eric/depot/vue/thirdparty/vite-plugin-cesium/demo/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:34107:11)
    at resolvePackageEntry (file:///Users/eric/depot/vue/thirdparty/vite-plugin-cesium/demo/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:34104:5)
    at tryNodeResolve (file:///Users/eric/depot/vue/thirdparty/vite-plugin-cesium/demo/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:33842:20)
    at file:///Users/eric/depot/vue/thirdparty/vite-plugin-cesium/demo/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:63090:40
    at requestCallbacks.on-resolve (/Users/eric/depot/vue/thirdparty/vite-plugin-cesium/demo/node_modules/esbuild/lib/main.js:1336:28)
    at handleRequest (/Users/eric/depot/vue/thirdparty/vite-plugin-cesium/demo/node_modules/esbuild/lib/main.js:706:19)
    at handleIncomingPacket (/Users/eric/depot/vue/thirdparty/vite-plugin-cesium/demo/node_modules/esbuild/lib/main.js:728:7)
    at Socket.readFromStdout (/Users/eric/depot/vue/thirdparty/vite-plugin-cesium/demo/node_modules/esbuild/lib/main.js:656:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)

  This error came from the "onResolve" callback registered here:

    node_modules/esbuild/lib/main.js:1260:20:
      1260 │       let promise = setup({
           ╵                     ^

    at setup (file:///Users/eric/depot/vue/thirdparty/vite-plugin-cesium/demo/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:63080:27)
    at handlePlugins (/Users/eric/depot/vue/thirdparty/vite-plugin-cesium/demo/node_modules/esbuild/lib/main.js:1260:21)
    at buildOrServeImpl (/Users/eric/depot/vue/thirdparty/vite-plugin-cesium/demo/node_modules/esbuild/lib/main.js:951:5)
    at Object.buildOrServe (/Users/eric/depot/vue/thirdparty/vite-plugin-cesium/demo/node_modules/esbuild/lib/main.js:759:5)
    at /Users/eric/depot/vue/thirdparty/vite-plugin-cesium/demo/node_modules/esbuild/lib/main.js:2096:17
    at new Promise (<anonymous>)
    at Object.build (/Users/eric/depot/vue/thirdparty/vite-plugin-cesium/demo/node_modules/esbuild/lib/main.js:2095:14)
    at build (/Users/eric/depot/vue/thirdparty/vite-plugin-cesium/demo/node_modules/esbuild/lib/main.js:1942:51)
    at bundleConfigFile (file:///Users/eric/depot/vue/thirdparty/vite-plugin-cesium/demo/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:63043:26)

  The plugin "externalize-deps" was triggered by this import

    vite.config.ts:2:19:
      2 │ import cesium from 'vite-plugin-cesium';
        ╵                    ~~~~~~~~~~~~~~~~~~~~

failed to load config from /Users/eric/depot/vue/thirdparty/vite-plugin-cesium/demo/vite.config.ts
error when starting dev server:
Error: Build failed with 1 error:
node_modules/esbuild/lib/main.js:1336:27: ERROR: [plugin: externalize-deps] Failed to resolve entry for package "vite-plugin-cesium". The package may have incorrect main/module/exports specified in its package.json.
    at failureErrorWithLog (/Users/eric/depot/vue/thirdparty/vite-plugin-cesium/demo/node_modules/esbuild/lib/main.js:1575:15)
    at /Users/eric/depot/vue/thirdparty/vite-plugin-cesium/demo/node_modules/esbuild/lib/main.js:1033:28
    at runOnEndCallbacks (/Users/eric/depot/vue/thirdparty/vite-plugin-cesium/demo/node_modules/esbuild/lib/main.js:1447:61)
    at buildResponseToResult (/Users/eric/depot/vue/thirdparty/vite-plugin-cesium/demo/node_modules/esbuild/lib/main.js:1031:7)
    at /Users/eric/depot/vue/thirdparty/vite-plugin-cesium/demo/node_modules/esbuild/lib/main.js:1143:14
    at responseCallbacks.<computed> (/Users/eric/depot/vue/thirdparty/vite-plugin-cesium/demo/node_modules/esbuild/lib/main.js:680:9)
    at handleIncomingPacket (/Users/eric/depot/vue/thirdparty/vite-plugin-cesium/demo/node_modules/esbuild/lib/main.js:735:9)
    at Socket.readFromStdout (/Users/eric/depot/vue/thirdparty/vite-plugin-cesium/demo/node_modules/esbuild/lib/main.js:656:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
```

Perhaps I missed a step?

**Comment by eric-g-97477** [comment]
I figured out what was wrong. I needed to run `yarn` and `yarn build` in the main plugin directory first as the demo refers to it.
